name: 'Rudra'
description: 'Rudra is a static analyzer to detect common undefined behaviors in Rust programs'
on:
  pull_request:
    branches:
      - develop
      - master
jobs:
  # Run Rudra
  - name: Rudra
    uses: sslab-gatech/Rudra@master